name: Java Version

on:
  push:
    branches:
    - master
    - release/*
jobs:
  build:
    strategy:
      matrix:
        java: [ '1.6', '9.0.x', '12.0.2' ]
    runs-on: ubuntu-18.04
    name: Java v${{ matrix.java }} 
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: java -version
  test:
    name: Unit test
    runs-on: ubuntu-18.04
    steps:
      - name: Date
        run: |
          echo $GHE_TOKEN | pbcopy
          pbpaste | wc -c
          
        env:
          GHE_TOKEN: ${{secrets.GHE_TOKEN}} 
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Date
        run: date
